export {
  ChooseSpecialtyRequestSchema,
  FrequentSpecialtiesSchema,
  isSpecialtyBookMember,
  normalizeSpecialtyQuery,
  SPECIALTY_CODE_MAX_LENGTH,
  SPECIALTY_CODE_REGEX,
  SPECIALTY_ERROR_CODES,
  SPECIALTY_NAME_MAX_LENGTH,
  SPECIALTY_OTHER_CODE,
  SPECIALTY_SEARCH_QUERY_MAX_LENGTH,
  SpecialtyBookSchema,
  SpecialtyChoiceSchema,
  SpecialtyCodeSchema,
  SpecialtyErrorCodeSchema,
  specialtyNameMatchesQuery,
  SpecialtyProblemDetailsSchema,
  SpecialtyReferenceSchema,
  SpecialtyRefSchema,
  SpecialtySearchQuerySchema,
  SpecialtySearchResultSchema,
  type ChooseSpecialtyRequest,
  type FrequentSpecialties,
  type SpecialtyBook,
  type SpecialtyChoice,
  type SpecialtyErrorCode,
  type SpecialtyProblemDetails,
  type SpecialtyRef,
  type SpecialtySearchResult,
} from './specialties.schema.js';
