// AUTO-GENERATED by packages/glossary/scripts/generate.ts — DO NOT EDIT.
// Run `pnpm generate:glossary` to regenerate. Verified by the `glossary-roundtrip` guard.
export const GLOSSARY_IDS = {
  consent_gate: "consent_gate",
  doctor_guest: "doctor_guest",
  enumeration_resistance: "enumeration_resistance",
  user_mirror: "user_mirror",
} as const;

export type GlossaryId = keyof typeof GLOSSARY_IDS;

export interface GlossaryTerm {
  id: GlossaryId;
  title: string;
  description: string;
  boundedContext: string;
  lang: string;
}

export const GLOSSARY_TERMS: readonly GlossaryTerm[] = [
  { id: "consent_gate", title: "consent gate", description: "The registration-time rule that no personal-data row is created before the registrant's per-purpose, versioned consent is recorded.", boundedContext: "compliance", lang: "en" },
  { id: "doctor_guest", title: "doctor_guest", description: "The v1 self-service backend role and mirror identity granted to a net-new visitor who self-registers on the doctor portal.", boundedContext: "identity", lang: "en" },
  { id: "enumeration_resistance", title: "enumeration resistance", description: "Returning identical responses for existing vs unknown identifiers on auth surfaces, so an attacker cannot probe which accounts exist.", boundedContext: "identity", lang: "en" },
  { id: "user_mirror", title: "domain user mirror", description: "The backend users row that projects a Zitadel identity into the domain — the UserMirror produced and reconciled by the auth feature.", boundedContext: "identity", lang: "en" },
];
