-- 010 — Universal edit audit (spec 010-universal-edit-audit, Issue #1087):
-- one generic PL/pgSQL row-level AFTER trigger capturing every INSERT/UPDATE/
-- DELETE of a domain table into the as-built append-only audit_ledger as
-- data.<table>.<insert|update|delete> rows (EARS-1, EARS-6). Hand-managed SQL —
-- drizzle-kit does not model triggers/functions (same pattern as the ledger's
-- partition DDL in 0003; ADR-0003 §3.4).
--
-- Attribution rides per-transaction GUCs (design §3): the API's Drizzle
-- transaction wrapper (EARS-3, #1088) issues SET LOCAL app.actor_sub /
-- app.source; the trigger reads both with current_setting(..., true) so a
-- context-less write (psql, unwrapped script) still lands one honest row with
-- source='db-direct' and a NULL actor — audited, never blocked (EARS-4).
-- NULLIF guards the empty-string form a reset custom GUC can take.
--
-- The append itself is fail-closed IN-transaction: if the ledger INSERT fails,
-- the domain mutation rolls back — no unaudited mutation ever commits
-- (010-requirements → Constraints). Only attribution degrades gracefully.
--
-- PD masking (EARS-7, ADR-0009 §2.4): PD-bearing columns (users,
-- consent_records — registry below) appear in diffs as {"masked": true} with
-- old/new omitted; presence proves THAT the field changed, values never land
-- in the ledger. TS mirror: packages/db/src/audit.ts (parity is e2e-enforced).

-- ── PD-column registry (design §5: array baked into the diff function,
--    regenerated by migration when the ADR-0009 matrix classifies a new
--    PD-bearing table). users.zitadel_sub is NOT PD (opaque sub, as-built
--    ledger contract).
CREATE OR REPLACE FUNCTION audit_pd_columns(p_table text) RETURNS text[] AS $$
  SELECT CASE p_table
    WHEN 'users' THEN ARRAY['email', 'phone', 'display_name']
    WHEN 'consent_records' THEN ARRAY['user_id']
    ELSE ARRAY[]::text[]
  END;
$$ LANGUAGE sql IMMUTABLE;
--> statement-breakpoint
-- ── Field-level diff (EARS-2): UPDATE = changed fields only (IS DISTINCT
--    FROM), {field:{old,new}}, bookkeeping column updated_at excluded; INSERT =
--    full new row {field:{new}}; DELETE = full old row {field:{old}} so a
--    deleted record stays reconstructible. PD columns emit {"masked": true}.
CREATE OR REPLACE FUNCTION audit_compute_diff(
  p_op text, p_table text, p_old jsonb, p_new jsonb
) RETURNS jsonb AS $$
DECLARE
  v_pd   text[] := audit_pd_columns(p_table);
  v_diff jsonb;
BEGIN
  IF p_op = 'INSERT' THEN
    SELECT coalesce(jsonb_object_agg(e.key,
             CASE WHEN e.key = ANY (v_pd) THEN jsonb_build_object('masked', true)
                  ELSE jsonb_build_object('new', e.value) END), '{}'::jsonb)
      INTO v_diff
      FROM jsonb_each(p_new) AS e(key, value);
  ELSIF p_op = 'DELETE' THEN
    SELECT coalesce(jsonb_object_agg(e.key,
             CASE WHEN e.key = ANY (v_pd) THEN jsonb_build_object('masked', true)
                  ELSE jsonb_build_object('old', e.value) END), '{}'::jsonb)
      INTO v_diff
      FROM jsonb_each(p_old) AS e(key, value);
  ELSE
    -- UPDATE: key union via merged object covers columns added/dropped
    -- mid-flight; only keys whose value actually changed survive.
    SELECT coalesce(jsonb_object_agg(k.key,
             CASE WHEN k.key = ANY (v_pd) THEN jsonb_build_object('masked', true)
                  ELSE jsonb_build_object('old', p_old -> k.key,
                                          'new', p_new -> k.key) END), '{}'::jsonb)
      INTO v_diff
      FROM jsonb_object_keys(p_old || p_new) AS k(key)
     WHERE k.key <> 'updated_at'
       AND (p_old -> k.key) IS DISTINCT FROM (p_new -> k.key);
  END IF;
  RETURN v_diff;
END $$ LANGUAGE plpgsql IMMUTABLE;
--> statement-breakpoint
-- ── Generic pk extraction (EARS-6): metadata.pk as jsonb, composite-PK-safe —
--    reads the table's PRIMARY KEY columns from the catalog, zero per-table code.
CREATE OR REPLACE FUNCTION audit_extract_pk(p_relid oid, p_row jsonb)
RETURNS jsonb AS $$
  SELECT coalesce(jsonb_object_agg(a.attname, p_row -> a.attname), '{}'::jsonb)
    FROM pg_index i
    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY (i.indkey)
   WHERE i.indrelid = p_relid AND i.indisprimary;
$$ LANGUAGE sql STABLE;
--> statement-breakpoint
-- ── The single generic capture function (EARS-1): table-agnostic
--    (TG_TABLE_NAME + to_jsonb(OLD/NEW)); covering a new table costs only its
--    CREATE TRIGGER line. Row-level AFTER — fires per affected row (a bulk
--    UPDATE of N rows yields N trail rows sharing txid) and cannot alter the
--    domain write. A no-op UPDATE (empty post-exclusion diff) writes no row.
CREATE OR REPLACE FUNCTION audit_row_change() RETURNS trigger AS $$
DECLARE
  v_actor  text  := nullif(current_setting('app.actor_sub', true), '');
  v_source text  := coalesce(nullif(current_setting('app.source', true), ''),
                             'db-direct');
  v_old    jsonb := CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END;
  v_new    jsonb := CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END;
  v_diff   jsonb;
BEGIN
  v_diff := audit_compute_diff(TG_OP, TG_TABLE_NAME, v_old, v_new);
  IF TG_OP = 'UPDATE' AND v_diff = '{}'::jsonb THEN
    RETURN NULL; -- the trail records changes, not touches (EARS-2)
  END IF;
  INSERT INTO audit_ledger (id, event_id, event_type, subject_id, metadata, created_at)
  VALUES (
    gen_random_uuid(),
    gen_random_uuid(),
    format('data.%s.%s', TG_TABLE_NAME, lower(TG_OP)),
    v_actor,
    jsonb_build_object(
      'table',  TG_TABLE_NAME,
      'pk',     audit_extract_pk(TG_RELID, coalesce(v_new, v_old)),
      'diff',   v_diff,
      'source', v_source,
      'txid',   txid_current()::text
    ),
    now()
  );
  RETURN NULL; -- AFTER trigger: return value ignored
END $$ LANGUAGE plpgsql;
--> statement-breakpoint
-- ── Per-table attachment (EARS-1): every current domain table opts in with one
--    line. Allowlisted with recorded rationale (design §5), NO trigger:
--    audit_ledger (recursion — the ledger cannot audit itself),
--    idempotency_keys (technical request-dedup cache, no domain truth),
--    presence_beats (append-only telemetry stream, itself an event log —
--    auditing would duplicate it 1:1 with no WHO/WHAT gain).
CREATE TRIGGER users_audit AFTER INSERT OR UPDATE OR DELETE
  ON "users" FOR EACH ROW EXECUTE FUNCTION audit_row_change();
--> statement-breakpoint
CREATE TRIGGER consent_records_audit AFTER INSERT OR UPDATE OR DELETE
  ON "consent_records" FOR EACH ROW EXECUTE FUNCTION audit_row_change();
--> statement-breakpoint
CREATE TRIGGER events_audit AFTER INSERT OR UPDATE OR DELETE
  ON "events" FOR EACH ROW EXECUTE FUNCTION audit_row_change();
--> statement-breakpoint
CREATE TRIGGER event_speakers_audit AFTER INSERT OR UPDATE OR DELETE
  ON "event_speakers" FOR EACH ROW EXECUTE FUNCTION audit_row_change();
--> statement-breakpoint
CREATE TRIGGER stream_config_audit AFTER INSERT OR UPDATE OR DELETE
  ON "stream_config" FOR EACH ROW EXECUTE FUNCTION audit_row_change();
--> statement-breakpoint
CREATE TRIGGER registrations_audit AFTER INSERT OR UPDATE OR DELETE
  ON "registrations" FOR EACH ROW EXECUTE FUNCTION audit_row_change();
