/**
 * Style Dictionary token-build (#233 / spec §2.2).
 *
 * Reads the DTCG token source in `tokens/*.json` (primitive -> semantic ->
 * component, references flowing only upward) and emits:
 *
 *   - src/styles/tokens.css           a Tailwind v4 `@theme` block + `:root` /
 *                                     `.dark` CSS custom properties. Dark
 *                                     overrides ONLY the semantic color layer;
 *                                     primitives are never duplicated per theme.
 *   - src/styles/allowed-tokens.json  a machine-readable list of every emitted
 *                                     token (consumed by the lint guardrails,
 *                                     #234).
 *
 * Reference resolution is validated: `getPlatformTokens` throws if any
 * `{group.token}` reference is unresolved, so the build fails loudly. We also
 * assert defensively afterwards.
 *
 * Phasing (spec §2.2 "Phased-with-JSON"): only the web (CSS) target is built.
 * The React-Native / native target is a commented-out placeholder at the bottom
 * of this file — adding it later is "add a platform target", not a token rewrite.
 *
 * Run with: `pnpm --filter @ds/design-system build`
 */
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import StyleDictionary from "style-dictionary";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(__dirname, "tokens");
const STYLES_DIR = join(__dirname, "src", "styles");

const GENERATED_HEADER =
  "/* GENERATED by Style Dictionary — do not edit. Source: packages/design-system/tokens/*.json. Run `pnpm --filter @ds/design-system build`. */";

/** Build + resolve a token tree over a chosen set of source files. Throws on a dangling reference. */
async function resolveTokens(sources) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: sources,
    // A real `css` platform so getPlatformTokens can resolve references.
    platforms: { css: { transformGroup: "css" } },
    // Collision "warnings" here are benign merge-time notices ($type group
    // headers shared across the layered source files) — the resolved output has
    // zero duplicate names (verified) and we validate references ourselves via
    // assertNoDanglingRefs. Silence them to keep CI output clean; a genuine
    // dangling reference still throws from getPlatformTokens.
    log: { verbosity: "default", warnings: "disabled" },
  });
  await sd.hasInitialized;
  const res = await sd.getPlatformTokens("css");
  return res.tokens ?? res;
}

/**
 * Flatten a resolved DTCG token tree into `{ path, value, type }` leaves.
 * `$value` has already been reference-resolved by Style Dictionary.
 */
function flatten(node, path, out) {
  if (node == null || typeof node !== "object") return;
  if (Object.prototype.hasOwnProperty.call(node, "$value")) {
    out.push({ path, value: node.$value, type: node.$type });
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    flatten(child, [...path, key], out);
  }
}

/** `["color","primary-foreground"]` -> `color-primary-foreground`. */
function cssName(path) {
  return path.join("-");
}

/** Format a resolved DTCG value into a CSS-usable string. */
function cssValue(token) {
  const { value, type } = token;
  if (Array.isArray(value)) {
    if (type === "fontFamily") {
      return value.map((f) => (/[\s]/.test(f) ? `"${f}"` : f)).join(", ");
    }
    if (type === "cubicBezier") {
      return `cubic-bezier(${value.join(", ")})`;
    }
    return value.join(", ");
  }
  return String(value);
}

/** The semantic color role names (e.g. primary, muted-foreground) — the ONLY
 * `color.*` tokens that surface as Tailwind theme colors / get a `.dark`
 * override. Read from semantic.json so primitives (white/black/neutral/red)
 * never leak into `@theme` (which would self-reference) or `.dark`. */
function semanticColorRoles() {
  const raw = JSON.parse(
    readFileSync(join(TOKENS_DIR, "semantic.json"), "utf8"),
  );
  return new Set(
    Object.keys(raw.color ?? {}).filter((k) => !k.startsWith("$")),
  );
}

/**
 * Map a token path onto a Tailwind v4 `@theme` namespace variable, so the
 * existing utilities (`bg-primary`, `font-sans`, `text-2xl`, …) resolve to our
 * tokens. Returns null for tokens that stay plain `:root` vars only (radius
 * scale + animations are appended manually). `roles` gates color tokens to the
 * semantic role set.
 */
function themeVar(path, roles) {
  const [head, ...rest] = path;
  switch (head) {
    case "color":
      // Only the semantic color roles surface as Tailwind colors.
      return rest.length === 1 && roles.has(rest[0])
        ? `--color-${rest.join("-")}`
        : null;
    case "font":
      if (rest[0] === "family") return `--font-${rest.slice(1).join("-")}`;
      if (rest[0] === "size") return `--text-${rest.slice(1).join("-")}`;
      if (rest[0] === "weight") return `--font-weight-${rest.slice(1).join("-")}`;
      return null;
    case "space":
      // The `space.*` primitives surface ONLY as `:root` `--space-N` vars and as
      // the derived `spacingScalePx` (rhythmguard). They are deliberately NOT
      // mapped onto a Tailwind `@theme` namespace: under Tailwind v4 the numeric
      // spacing utilities (`p-4`, `gap-2`, `h-10`) derive from the single
      // `--spacing` multiplier via `calc()`, so per-step `--spacing-N` `@theme`
      // keys drive no utility — emitting them only advertised an inert mapping a
      // reader would misread as "`p-4` → `--spacing-4`" (it does not). Dropped in
      // #243. See the spacing-scale note in build() for the SoT derivation.
      return null;
    case "shadow":
      return `--shadow-${rest.join("-")}`;
    case "breakpoint":
      return `--breakpoint-${rest.join("-")}`;
    default:
      return null;
  }
}

async function build() {
  // --- light tree: primitive + semantic + component ------------------------
  const lightTokens = await resolveTokens([
    join(TOKENS_DIR, "primitive.json"),
    join(TOKENS_DIR, "semantic.json"),
    join(TOKENS_DIR, "component.json"),
  ]);
  const lightLeaves = [];
  flatten(lightTokens, [], lightLeaves);
  assertNoDanglingRefs(lightLeaves, "light");

  // --- dark tree: primitive + semantic + dark overrides --------------------
  const darkTokens = await resolveTokens([
    join(TOKENS_DIR, "primitive.json"),
    join(TOKENS_DIR, "semantic.json"),
    join(TOKENS_DIR, "semantic.dark.json"),
  ]);
  const darkLeaves = [];
  flatten(darkTokens, [], darkLeaves);
  assertNoDanglingRefs(darkLeaves, "dark");

  const roles = semanticColorRoles();

  // `:root` custom properties = every light leaf (primitive + semantic +
  // component) EXCEPT breakpoints, which are emitted as literal `@theme` values
  // only (they drive `@media` queries and must not be runtime `var()`s).
  const rootVars = lightLeaves
    .filter((l) => l.path[0] !== "breakpoint")
    .map((l) => ({
      name: `--${cssName(l.path)}`,
      value: cssValue(l),
    }));

  // `.dark` overrides = only the semantic color ROLES (never primitives).
  const isColorRole = (l) =>
    l.path[0] === "color" && l.path.length === 2 && roles.has(l.path[1]);
  const darkVars = darkLeaves.filter(isColorRole).map((l) => ({
    name: `--${cssName(l.path)}`,
    value: cssValue(l),
  }));

  // `@theme` keys -> point at the `:root` var so utilities resolve to tokens and
  // dark-mode overrides flow through automatically. EXCEPTION: breakpoints must
  // be LITERAL values, never `var(...)` — Tailwind v4 inlines them into
  // `@media (width >= …)` queries, and a `var()` is invalid inside a media query.
  const themeEntries = [];
  for (const l of lightLeaves) {
    const tv = themeVar(l.path, roles);
    if (!tv) continue;
    const ref =
      l.path[0] === "breakpoint"
        ? cssValue(l)
        : `var(--${cssName(l.path)})`;
    themeEntries.push({ name: tv, ref });
  }
  // Radius scale: derive Tailwind's rounded-sm|md|lg|xl from semantic radius.control.
  themeEntries.push(
    { name: "--radius-sm", ref: "calc(var(--radius-control) - 4px)" },
    { name: "--radius-md", ref: "calc(var(--radius-control) - 2px)" },
    { name: "--radius-lg", ref: "var(--radius-control)" },
    { name: "--radius-xl", ref: "calc(var(--radius-control) + 4px)" },
  );
  // The caret-blink animation utility lives with the tokens it animates.
  themeEntries.push({
    name: "--animate-caret-blink",
    ref: "caret-blink 1.25s ease-out infinite",
  });

  // --- assemble tokens.css -------------------------------------------------
  const css = [
    GENERATED_HEADER,
    "",
    ":root {",
    ...rootVars.map((v) => `  ${v.name}: ${v.value};`),
    "}",
    "",
    ".dark {",
    ...darkVars.map((v) => `  ${v.name}: ${v.value};`),
    "}",
    "",
    "@theme inline {",
    ...themeEntries.map((e) => `  ${e.name}: ${e.ref};`),
    "}",
    "",
  ].join("\n");

  mkdirSync(STYLES_DIR, { recursive: true });
  writeFileSync(join(STYLES_DIR, "tokens.css"), css, "utf8");

  // --- effective spacing scale (px) — derived, for the rhythmguard gate ----
  // The `space.*` tokens are the single source of truth for spacing: they emit
  // as `:root` `--space-N` vars, and the rhythmguard's allowed scale is derived
  // here from their resolved VALUES (rem→px at 16px root), so styling and linting
  // share one generated source. We do NOT emit per-step `--spacing-N` `@theme`
  // keys (dropped in #243): under Tailwind v4 the numeric spacing utilities
  // (`p-4`, `gap-2`) derive from the single `--spacing` multiplier via `calc()`,
  // so named per-step keys are inert for them — the lint scale therefore reads
  // the effective px values, never the token names.
  const REM_PX = 16;
  const spacingScalePx = Array.from(
    new Set(
      lightLeaves
        .filter((l) => l.path[0] === "space")
        .map((l) => {
          const raw = String(l.value).trim();
          if (raw.endsWith("rem")) return parseFloat(raw) * REM_PX;
          if (raw.endsWith("px")) return parseFloat(raw);
          if (raw === "0") return 0;
          return null;
        })
        .filter((n) => n !== null && Number.isFinite(n)),
    ),
  ).sort((a, b) => a - b);

  // --- allowed-tokens.json (consumed by lint guardrails, #234) -------------
  const allowed = {
    $generatedBy: "style-dictionary",
    $description:
      "Machine-readable enumeration of every token emitted by the token-build. Consumed by the lint guardrails (#234) so styling and linting share one source of truth.",
    cssVariables: rootVars.map((v) => v.name).sort(),
    themeKeys: themeEntries.map((e) => e.name).sort(),
    tokenPaths: lightLeaves.map((l) => l.path.join(".")).sort(),
    // Effective spacing scale in px (derived from the `space.*` token VALUES, not
    // the inert `--spacing-N` names) — the allowed scale for the rhythmguard
    // arbitrary-spacing gate. See the decision-debt note above.
    spacingScalePx,
  };
  writeFileSync(
    join(STYLES_DIR, "allowed-tokens.json"),
    JSON.stringify(allowed, null, 2) + "\n",
    "utf8",
  );

  console.log(
    `[tokens] wrote ${rootVars.length} :root vars, ${darkVars.length} .dark overrides, ${themeEntries.length} @theme keys, ${allowed.tokenPaths.length} allowed tokens, spacing scale [${spacingScalePx.join(", ")}]px.`,
  );
}

/** Defensive assert: no `$value` still contains an unresolved `{ref}`. */
function assertNoDanglingRefs(leaves, label) {
  const bad = leaves.filter(
    (l) => typeof l.value === "string" && /\{[^}]+\}/.test(l.value),
  );
  if (bad.length > 0) {
    const list = bad.map((l) => `  ${l.path.join(".")} = ${l.value}`).join("\n");
    throw new Error(
      `[tokens] ${bad.length} dangling reference(s) in the ${label} tree:\n${list}`,
    );
  }
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});

// ---------------------------------------------------------------------------
// PHASED placeholder — React-Native / native target (spec §2.2, ADR-0005).
// Deliberately NOT built in this iteration. When the mobile app starts, add a
// native emit here (e.g. a JS/TS object or RN StyleSheet) over the SAME token
// source — that is "add a platform target", not a token rewrite.
//
//   const nativeSD = new StyleDictionary({ usesDtcg: true, source: [...same...],
//     platforms: { "react-native": { transformGroup: "react-native",
//       buildPath: "src/native/", files: [{ destination: "tokens.ts",
//       format: "javascript/es6" }] } } });
//   await nativeSD.buildPlatform("react-native");
// ---------------------------------------------------------------------------
