/**
 * Style Dictionary token-build (#233 / spec §2.2).
 *
 * Reads the DTCG token source in `tokens/*.json` (primitive -> semantic ->
 * component, references flowing only upward) and emits:
 *
 *   - src/styles/tokens.css           a Tailwind v4 `@theme` block + `:root` /
 *                                     `.dark` CSS custom properties. Dark
 *                                     overrides ONLY the semantic color layer;
 *                                     primitives are never duplicated per theme.
 *   - src/styles/allowed-tokens.json  a machine-readable list of every emitted
 *                                     token (consumed by the lint guardrails,
 *                                     #234).
 *
 * Reference resolution is validated: `getPlatformTokens` throws if any
 * `{group.token}` reference is unresolved, so the build fails loudly. We also
 * assert defensively afterwards.
 *
 * Phasing (spec §2.2 "Phased-with-JSON"): only the web (CSS) target is built.
 * The React-Native / native target is a commented-out placeholder at the bottom
 * of this file — adding it later is "add a platform target", not a token rewrite.
 *
 * Run with: `pnpm --filter @ds/design-system build`
 */
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import StyleDictionary from "style-dictionary";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(__dirname, "tokens");
const STYLES_DIR = join(__dirname, "src", "styles");

const GENERATED_HEADER =
  "/* GENERATED by Style Dictionary — do not edit. Source: packages/design-system/tokens/*.json. Run `pnpm --filter @ds/design-system build`. */";

/** Build + resolve a token tree over a chosen set of source files. Throws on a dangling reference. */
async function resolveTokens(sources) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: sources,
    // A real `css` platform so getPlatformTokens can resolve references.
    platforms: { css: { transformGroup: "css" } },
    // Collision "warnings" here are benign merge-time notices ($type group
    // headers shared across the layered source files) — the resolved output has
    // zero duplicate names (verified) and we validate references ourselves via
    // assertNoDanglingRefs. Silence them to keep CI output clean; a genuine
    // dangling reference still throws from getPlatformTokens.
    log: { verbosity: "default", warnings: "disabled" },
  });
  await sd.hasInitialized;
  const res = await sd.getPlatformTokens("css");
  return res.tokens ?? res;
}

/**
 * Flatten a resolved DTCG token tree into `{ path, value, type }` leaves.
 * `$value` has already been reference-resolved by Style Dictionary.
 */
function flatten(node, path, out) {
  if (node == null || typeof node !== "object") return;
  if (Object.prototype.hasOwnProperty.call(node, "$value")) {
    out.push({ path, value: node.$value, type: node.$type });
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    flatten(child, [...path, key], out);
  }
}

/** `["color","primary-foreground"]` -> `color-primary-foreground`. */
function cssName(path) {
  return path.join("-");
}

/**
 * Read the RAW DTCG source (before Style Dictionary resolves references) to
 * capture, per emitted token: (a) its REFERENCE — the `{group.token}` alias it
 * points at, as a CSS-var name — and (b) its `$description` usage note. Both
 * keyed by CSS-var name so they line up with `cssVariables`. The showcase reads
 * these to make the primitive→semantic layering and the "use this for…" guidance
 * legible on the page (#370), so a role like `card` shows it aliases `white` and
 * what it is for — no second source of truth, no hardcoding in the viewer.
 */
function readRawMeta(files) {
  const references = {};
  const descriptions = {};
  const visit = (node, path) => {
    if (node == null || typeof node !== "object") return;
    if (Object.prototype.hasOwnProperty.call(node, "$value")) {
      const name = `--${cssName(path)}`;
      if (typeof node.$value === "string") {
        const m = node.$value.match(/^\{([^}]+)\}$/);
        if (m) references[name] = `--${m[1].split(".").join("-")}`;
      }
      if (typeof node.$description === "string") {
        descriptions[name] = node.$description;
      }
      return;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith("$")) continue;
      visit(child, [...path, key]);
    }
  };
  for (const file of files) visit(JSON.parse(readFileSync(file, "utf8")), []);
  return { references, descriptions };
}

/** Format a resolved DTCG value into a CSS-usable string. */
function cssValue(token) {
  const { value, type } = token;
  if (Array.isArray(value)) {
    if (type === "fontFamily") {
      return value.map((f) => (/[\s]/.test(f) ? `"${f}"` : f)).join(", ");
    }
    if (type === "cubicBezier") {
      return `cubic-bezier(${value.join(", ")})`;
    }
    return value.join(", ");
  }
  return String(value);
}

/** The semantic color role names (e.g. primary, muted-foreground) — the ONLY
 * `color.*` tokens that surface as Tailwind theme colors / get a `.dark`
 * override. Read from semantic.json so primitives (white/black/neutral/red)
 * never leak into `@theme` (which would self-reference) or `.dark`. */
function semanticColorRoles() {
  const raw = JSON.parse(
    readFileSync(join(TOKENS_DIR, "semantic.json"), "utf8"),
  );
  return new Set(
    Object.keys(raw.color ?? {}).filter((k) => !k.startsWith("$")),
  );
}

/** The semantic spacing ROLE names (inset, stack, section, controls, inline,
 * day-band, gutter) defined under `semantic.json` `space.*`. These — and ONLY
 * these — surface as named Tailwind spacing utilities via the `--spacing-<role>`
 * @theme namespace; the numeric `space.N` primitives stay unmapped (§243 note in
 * themeVar). Read from source so a new role added to semantic.json flows through. */
function semanticSpaceRoles() {
  const raw = JSON.parse(
    readFileSync(join(TOKENS_DIR, "semantic.json"), "utf8"),
  );
  return new Set(
    Object.keys(raw.space ?? {}).filter((k) => !k.startsWith("$")),
  );
}

/**
 * Map a token path onto a Tailwind v4 `@theme` namespace variable, so the
 * existing utilities (`bg-primary`, `font-sans`, `text-2xl`, …) resolve to our
 * tokens. Returns null for tokens that stay plain `:root` vars only (radius
 * scale + animations are appended manually). `roles` gates color tokens to the
 * semantic role set.
 */
function themeVar(path, colorRoles, spaceRoles) {
  const [head, ...rest] = path;
  switch (head) {
    case "color":
      // Only the semantic color roles surface as Tailwind colors.
      return rest.length === 1 && colorRoles.has(rest[0])
        ? `--color-${rest.join("-")}`
        : null;
    case "font":
      if (rest[0] === "family") return `--font-${rest.slice(1).join("-")}`;
      if (rest[0] === "size") return `--text-${rest.slice(1).join("-")}`;
      if (rest[0] === "weight")
        return `--font-weight-${rest.slice(1).join("-")}`;
      return null;
    case "space":
      // The numeric `space.N` PRIMITIVES surface ONLY as `:root` `--space-N` vars
      // and as the derived `spacingScalePx` (rhythmguard). They are deliberately
      // NOT mapped onto a Tailwind `@theme` namespace: under Tailwind v4 the
      // numeric spacing utilities (`p-4`, `gap-2`, `h-10`) derive from the single
      // `--spacing` multiplier via `calc()`, so per-step `--spacing-N` `@theme`
      // keys drive no utility (dropped in #243). The §09 semantic spacing ROLES
      // (semantic.json `space.<role>`) are the exception — a NAMED spacing key
      // (`--spacing-inset`) does drive a named utility (`p-inset`, `gap-controls`,
      // `space-y-section`, `-mx-gutter`, …), with no numeric collision — so those
      // and only those map through. See semanticSpaceRoles() / the README §09.
      return rest.length === 1 && spaceRoles.has(rest[0])
        ? `--spacing-${rest.join("-")}`
        : null;
    case "container":
      // §09 content-column max-widths → the Tailwind v4 `--container-*` namespace,
      // which generates `max-w-content` / `max-w-calendar`.
      return `--container-${rest.join("-")}`;
    case "shadow":
      return `--shadow-${rest.join("-")}`;
    case "breakpoint":
      return `--breakpoint-${rest.join("-")}`;
    default:
      return null;
  }
}

async function build() {
  // --- light tree: primitive + semantic + component ------------------------
  const lightTokens = await resolveTokens([
    join(TOKENS_DIR, "primitive.json"),
    join(TOKENS_DIR, "semantic.json"),
    join(TOKENS_DIR, "component.json"),
  ]);
  const lightLeaves = [];
  flatten(lightTokens, [], lightLeaves);
  assertNoDanglingRefs(lightLeaves, "light");

  // --- dark tree: primitive + semantic + dark overrides --------------------
  const darkTokens = await resolveTokens([
    join(TOKENS_DIR, "primitive.json"),
    join(TOKENS_DIR, "semantic.json"),
    join(TOKENS_DIR, "semantic.dark.json"),
  ]);
  const darkLeaves = [];
  flatten(darkTokens, [], darkLeaves);
  assertNoDanglingRefs(darkLeaves, "dark");

  const roles = semanticColorRoles();
  const spaceRoles = semanticSpaceRoles();

  // `:root` custom properties = every light leaf (primitive + semantic +
  // component) EXCEPT breakpoints, which are emitted as literal `@theme` values
  // only (they drive `@media` queries and must not be runtime `var()`s).
  const rootVars = lightLeaves
    .filter((l) => l.path[0] !== "breakpoint")
    .map((l) => ({
      name: `--${cssName(l.path)}`,
      value: cssValue(l),
    }));

  // `.dark` overrides = only the semantic color ROLES (never primitives).
  const isColorRole = (l) =>
    l.path[0] === "color" && l.path.length === 2 && roles.has(l.path[1]);
  const darkVars = darkLeaves.filter(isColorRole).map((l) => ({
    name: `--${cssName(l.path)}`,
    value: cssValue(l),
  }));

  // `.light` FORCED-LIGHT reset = the SAME semantic color roles at their light
  // values. `:root` already declares the light theme document-wide, but it cannot
  // reset a subtree nested INSIDE a `.dark` ancestor (custom properties inherit, so
  // a descendant with no theme class keeps the inherited `.dark` value). Emitting
  // the light roles under an explicit `.light` class lets a region force light
  // regardless of an ancestor theme — the mirror of `.dark`. Used by the showcase
  // to render its light/dark specimen pairs side-by-side under a runtime page-level
  // theme toggle (#515); a product app that pins a forced-light island (e.g. a
  // print preview) gets the same affordance. Only the semantic roles are emitted (never
  // primitives), exactly like `.dark`.
  const lightVars = lightLeaves.filter(isColorRole).map((l) => ({
    name: `--${cssName(l.path)}`,
    value: cssValue(l),
  }));

  // `@theme` keys -> point at the `:root` var so utilities resolve to tokens and
  // dark-mode overrides flow through automatically. EXCEPTION: breakpoints must
  // be LITERAL values, never `var(...)` — Tailwind v4 inlines them into
  // `@media (width >= …)` queries, and a `var()` is invalid inside a media query.
  const themeEntries = [];
  for (const l of lightLeaves) {
    const tv = themeVar(l.path, roles, spaceRoles);
    if (!tv) continue;
    const ref =
      l.path[0] === "breakpoint" ? cssValue(l) : `var(--${cssName(l.path)})`;
    themeEntries.push({ name: tv, ref });
  }
  // Radius scale: the neo-brutalist visual language is a FLAT, radius-0 system, so the
  // Tailwind rounded-sm|md|lg|xl ladder collapses onto `--radius-control` — every rung
  // resolves to the one control radius (0), and an adopted shadcn block's `rounded-md` /
  // `rounded-lg` / `rounded-xl` renders square, not with a leaked corner. A future rounded
  // theme would reintroduce proportional per-rung deltas here.
  themeEntries.push(
    { name: "--radius-sm", ref: "var(--radius-control)" },
    { name: "--radius-md", ref: "var(--radius-control)" },
    { name: "--radius-lg", ref: "var(--radius-control)" },
    { name: "--radius-xl", ref: "var(--radius-control)" },
  );
  // The caret-blink animation utility lives with the tokens it animates.
  themeEntries.push({
    name: "--animate-caret-blink",
    ref: "caret-blink 1.25s ease-out infinite",
  });
  // The `livePulse` feedback animation (badge live-dot + loading skeleton, #513),
  // exposed as two named `animate-*` utilities differing only in duration — the
  // source runs the live badge dot at 1.6s and the skeleton shimmer at 1.4s. Both
  // reference the ONE `live-pulse` keyframe defined in globals.css (alongside
  // caret-blink); the `prefers-reduced-motion` base-reset neutralises them.
  themeEntries.push(
    {
      name: "--animate-live-pulse",
      ref: "live-pulse 1.6s ease-in-out infinite",
    },
    {
      name: "--animate-skeleton-pulse",
      ref: "live-pulse 1.4s ease-in-out infinite",
    },
  );
  // Uppercase micro-label tracking as a token-backed `tracking-micro` utility
  // (#513). The foundation normalises every scattered uppercase eyebrow / badge /
  // day-band tracking (source 0.08–0.16em) onto the single micro-label token
  // (+0.12em, `--font-letter-spacing-micro`), so the badges and the day-band plate
  // resolve their tracking to one token rather than Tailwind's default ladder.
  themeEntries.push({
    name: "--tracking-micro",
    ref: "var(--font-letter-spacing-micro)",
  });
  // Numeric/time tracking as a token-backed `tracking-numeric` utility (#514).
  // The big tabular time on the webinar-card plate (56px desktop / 40px mobile,
  // source webinar-card.dc.html) tracks at −.04em — the `numeric` letter-spacing
  // token — which no default Tailwind rung carries (`tracking-tight` is −.025em).
  themeEntries.push({
    name: "--tracking-numeric",
    ref: "var(--font-letter-spacing-numeric)",
  });
  // The webinar-card time-plate width as a SIZING utility (`w-time-plate`, #514).
  // A named `--spacing-*` key drives the sizing utilities (`w-*` / `basis-*`) the
  // same way the §09 role keys drive gap/padding; the value lives in the component
  // token (component.json `webinar-card.time-plate`, 196px — source grid column).
  themeEntries.push({
    name: "--spacing-time-plate",
    ref: "var(--webinar-card-time-plate)",
  });

  // --- assemble tokens.css -------------------------------------------------
  const css = [
    GENERATED_HEADER,
    "",
    ":root {",
    ...rootVars.map((v) => `  ${v.name}: ${v.value};`),
    "}",
    "",
    ".dark {",
    ...darkVars.map((v) => `  ${v.name}: ${v.value};`),
    "}",
    "",
    // Forced-light reset — the light semantic roles under an explicit class so a
    // subtree can override an ancestor `.dark` (see lightVars above). Mirrors `.dark`.
    ".light {",
    ...lightVars.map((v) => `  ${v.name}: ${v.value};`),
    "}",
    "",
    "@theme inline {",
    ...themeEntries.map((e) => `  ${e.name}: ${e.ref};`),
    "}",
    "",
  ].join("\n");

  mkdirSync(STYLES_DIR, { recursive: true });
  writeFileSync(join(STYLES_DIR, "tokens.css"), css, "utf8");

  // --- effective spacing scale (px) — derived, for the rhythmguard gate ----
  // The `space.*` tokens are the single source of truth for spacing: they emit
  // as `:root` `--space-N` vars, and the rhythmguard's allowed scale is derived
  // here from their resolved VALUES (rem→px at 16px root), so styling and linting
  // share one generated source. We do NOT emit per-step `--spacing-N` `@theme`
  // keys (dropped in #243): under Tailwind v4 the numeric spacing utilities
  // (`p-4`, `gap-2`) derive from the single `--spacing` multiplier via `calc()`,
  // so named per-step keys are inert for them — the lint scale therefore reads
  // the effective px values, never the token names.
  const REM_PX = 16;
  const spacingScalePx = Array.from(
    new Set(
      lightLeaves
        .filter((l) => l.path[0] === "space")
        .map((l) => {
          const raw = String(l.value).trim();
          if (raw.endsWith("rem")) return parseFloat(raw) * REM_PX;
          if (raw.endsWith("px")) return parseFloat(raw);
          if (raw === "0") return 0;
          return null;
        })
        .filter((n) => n !== null && Number.isFinite(n)),
    ),
  ).sort((a, b) => a - b);

  // --- breakpoints (name -> literal value) ---------------------------------
  // Breakpoints are emitted ONLY as literal `@theme inline` values (above), never
  // as `:root` `--breakpoint-*` runtime vars — a `var()` is invalid inside the
  // `@media (width >= …)` query they drive. So `getComputedStyle` cannot read
  // them; the showcase tokens page (#346) reads their VALUES from here instead,
  // the same generated-SoT pattern as `spacingScalePx`. Keyed by the `@theme` var
  // name so it lines up with `themeKeys`.
  const breakpoints = lightLeaves
    .filter((l) => l.path[0] === "breakpoint")
    .map((l) => ({
      name: themeVar(l.path, roles, spaceRoles),
      value: cssValue(l),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  // --- token references + usage descriptions (raw source) ------------------
  // Read from the unresolved DTCG source so a semantic role keeps its `{primitive}`
  // reference and its `$description` (Style Dictionary resolves both away). The
  // showcase (#370) renders these so the layering + "use for" guidance is legible.
  const { references, descriptions } = readRawMeta([
    join(TOKENS_DIR, "primitive.json"),
    join(TOKENS_DIR, "semantic.json"),
    join(TOKENS_DIR, "component.json"),
  ]);

  // --- allowed-tokens.json (consumed by lint guardrails, #234) -------------
  const allowed = {
    $generatedBy: "style-dictionary",
    $description:
      "Machine-readable enumeration of every token emitted by the token-build. Consumed by the lint guardrails (#234) so styling and linting share one source of truth.",
    cssVariables: rootVars.map((v) => v.name).sort(),
    themeKeys: themeEntries.map((e) => e.name).sort(),
    tokenPaths: lightLeaves.map((l) => l.path.join(".")).sort(),
    // Effective spacing scale in px (derived from the `space.*` token VALUES, not
    // the inert `--spacing-N` names) — the allowed scale for the rhythmguard
    // arbitrary-spacing gate. See the decision-debt note above.
    spacingScalePx,
    // Breakpoint values (`@theme inline` literals, not `:root` vars — see above),
    // so the showcase can render them from the generated manifest, not hardcode.
    breakpoints,
    // Per-token reference (alias → primitive) and usage `$description`, read from
    // the raw source so the showcase can explain "which token, and what for" (#370).
    references,
    descriptions,
  };
  writeFileSync(
    join(STYLES_DIR, "allowed-tokens.json"),
    JSON.stringify(allowed, null, 2) + "\n",
    "utf8",
  );

  console.log(
    `[tokens] wrote ${rootVars.length} :root vars, ${darkVars.length} .dark overrides, ${lightVars.length} .light resets, ${themeEntries.length} @theme keys, ${allowed.tokenPaths.length} allowed tokens, spacing scale [${spacingScalePx.join(", ")}]px.`,
  );
}

/** Defensive assert: no `$value` still contains an unresolved `{ref}`. */
function assertNoDanglingRefs(leaves, label) {
  const bad = leaves.filter(
    (l) => typeof l.value === "string" && /\{[^}]+\}/.test(l.value),
  );
  if (bad.length > 0) {
    const list = bad
      .map((l) => `  ${l.path.join(".")} = ${l.value}`)
      .join("\n");
    throw new Error(
      `[tokens] ${bad.length} dangling reference(s) in the ${label} tree:\n${list}`,
    );
  }
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});

// ---------------------------------------------------------------------------
// PHASED placeholder — React-Native / native target (spec §2.2, ADR-0005).
// Deliberately NOT built in this iteration. When the mobile app starts, add a
// native emit here (e.g. a JS/TS object or RN StyleSheet) over the SAME token
// source — that is "add a platform target", not a token rewrite.
//
//   const nativeSD = new StyleDictionary({ usesDtcg: true, source: [...same...],
//     platforms: { "react-native": { transformGroup: "react-native",
//       buildPath: "src/native/", files: [{ destination: "tokens.ts",
//       format: "javascript/es6" }] } } });
//   await nativeSD.buildPlatform("react-native");
// ---------------------------------------------------------------------------
