CREATE EXTENSION vector;
CREATE EXTENSION citext;
CREATE EXTENSION pg_trgm;
CREATE SCHEMA partman;
CREATE EXTENSION pg_partman SCHEMA partman;
CREATE SCHEMA drill AUTHORIZATION fixture_owner;
SET ROLE fixture_owner;
CREATE TABLE drill.markers(marker text PRIMARY KEY);
CREATE TABLE drill.records(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, retained boolean NOT NULL, embedding vector(3) NOT NULL);
INSERT INTO drill.records(retained,embedding) VALUES (true,'[1,0,0]'),(false,'[0,1,0]');
CREATE INDEX ON drill.records USING hnsw (embedding vector_l2_ops);
GRANT USAGE ON SCHEMA drill TO fixture_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA drill TO fixture_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA drill GRANT SELECT ON TABLES TO fixture_reader;
RESET ROLE;
CREATE TABLE drill.events(id bigint NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY(created_at,id)) PARTITION BY RANGE(created_at);
SELECT partman.create_parent('drill.events','created_at','1 month');
UPDATE partman.part_config SET retention=NULL,retention_keep_table=true WHERE parent_table='drill.events';
INSERT INTO drill.events VALUES (1,now());
SELECT partman.run_maintenance('drill.events');
SELECT lo_from_bytea(12345,decode('73796e746865746963','hex'));
