CREATE EXTENSION vector;
CREATE EXTENSION citext;
CREATE EXTENSION pg_trgm;
CREATE SCHEMA partman;
CREATE EXTENSION pg_partman SCHEMA partman;
CREATE SCHEMA drill AUTHORIZATION fixture_owner;
SET ROLE fixture_owner;
CREATE TABLE drill.markers(marker text PRIMARY KEY);
CREATE TABLE drill.records(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, retained boolean NOT NULL, embedding vector(3) NOT NULL);
INSERT INTO drill.records(retained,embedding) VALUES (true,'[1,0,0]'),(false,'[0,1,0]');
CREATE INDEX ON drill.records USING hnsw (embedding vector_l2_ops);
GRANT USAGE ON SCHEMA drill TO fixture_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA drill TO fixture_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA drill GRANT SELECT ON TABLES TO fixture_reader;
RESET ROLE;
