#!/usr/bin/env tsx
/**
 * packages/glossary/scripts/generate.ts — the ADR-0006 §6.2 glossary generator.
 *
 * Reads the glossary source-of-truth (`apps/docs/content/product/glossary/*.md`,
 * Keystatic file-per-term) and emits two committed, generated artifacts:
 *
 *   1. `packages/glossary/src/ids.ts` — the `GLOSSARY_IDS` const (+ `GlossaryId`
 *      type + `GLOSSARY_TERMS` metadata). This is the artifact the
 *      `glossary-roundtrip` guard (`tools/lint/glossary-roundtrip-lint.ts`)
 *      diffs against the source id-set, and the `@ds/glossary-canonical-ids`
 *      ESLint rule imports. Committed to Git so it resolves on a fresh checkout
 *      before the generator runs.
 *   2. `packages/glossary/messages/<lang>/glossary.json` — one i18n label bundle
 *      per language present in the source (`lang` frontmatter). Each bundle maps
 *      canonical id → `{ title, description }`.
 *
 * ── Field mapping (reconciled to the REAL Keystatic format, #460) ─────────────
 * ADR-0006 §6.1 records that the §5/§6.2 sketches (a `label_ru`/`bounded_context`/
 * `related` frontmatter schema) predate the adopted shape. The real per-term file
 * carries Keystatic frontmatter `title` / `description` / `lang` PLUS body markers
 * `**Canonical id:** \`id\`` and `**Bounded context:** <ctx>`. This generator reads
 * that reality (same body-marker id the guards key on — see
 * `tools/lint/lib/glossary.ts`), NOT the obsolete sketch frontmatter. A source
 * file with no `**Canonical id:**` marker is skipped, mirroring the guard's reader
 * exactly, so the generated id-set stays in lockstep with what the roundtrip guard
 * derives from the source.
 *
 * Deterministic: terms are sorted by id, languages by name, JSON is 2-space +
 * trailing newline. Re-running produces byte-identical output.
 *
 * Run: `pnpm generate:glossary`.
 */
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import fg from "fast-glob";
import matter from "gray-matter";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const SRC_GLOB = "apps/docs/content/product/glossary/*.md";
const IDS_OUT = "packages/glossary/src/ids.ts";
const MESSAGES_DIR = "packages/glossary/messages";

/** ``**Canonical id:** `snake_id` `` — the authoritative id marker in the body. */
const CANONICAL_ID_RE = /\*\*Canonical id:\*\*\s*`([a-z][a-z0-9_]*)`/;
/** `**Bounded context:** <ctx>` — the bounded-context marker in the body. */
const BOUNDED_CONTEXT_RE = /\*\*Bounded context:\*\*\s*([a-z][a-z0-9_-]*)/i;

interface Term {
  id: string;
  title: string;
  description: string;
  boundedContext: string;
  lang: string;
}

async function readTerms(): Promise<Term[]> {
  const files = await fg(SRC_GLOB, { cwd: REPO_ROOT, ignore: ["**/node_modules/**"] });
  const terms: Term[] = [];
  for (const rel of files.sort()) {
    const raw = await readFile(resolve(REPO_ROOT, rel), "utf8");
    const idMatch = raw.match(CANONICAL_ID_RE);
    // Skip files with no canonical-id marker — mirrors the guard reader, keeping
    // the generated id-set in lockstep with the roundtrip guard's source set.
    if (!idMatch) continue;
    const { data } = matter(raw);
    const title = typeof data.title === "string" ? data.title.trim() : "";
    const description = typeof data.description === "string" ? data.description.trim() : "";
    const lang = typeof data.lang === "string" ? data.lang.trim() : "";
    if (!title || !lang) {
      throw new Error(`${rel}: glossary term \`${idMatch[1]}\` is missing frontmatter title/lang.`);
    }
    const bcMatch = raw.match(BOUNDED_CONTEXT_RE);
    if (!bcMatch) {
      throw new Error(`${rel}: glossary term \`${idMatch[1]}\` is missing a \`**Bounded context:**\` marker.`);
    }
    terms.push({ id: idMatch[1], title, description, boundedContext: bcMatch[1], lang });
  }
  terms.sort((a, b) => a.id.localeCompare(b.id));

  const seen = new Set<string>();
  for (const t of terms) {
    if (seen.has(t.id)) throw new Error(`Duplicate glossary canonical id \`${t.id}\`.`);
    seen.add(t.id);
  }
  return terms;
}

function renderIdsTs(terms: Term[]): string {
  const idLines = terms.map((t) => `  ${t.id}: ${JSON.stringify(t.id)},`).join("\n");
  const termLines = terms
    .map(
      (t) =>
        `  { id: ${JSON.stringify(t.id)}, title: ${JSON.stringify(t.title)}, ` +
        `description: ${JSON.stringify(t.description)}, ` +
        `boundedContext: ${JSON.stringify(t.boundedContext)}, lang: ${JSON.stringify(t.lang)} },`,
    )
    .join("\n");
  return `// AUTO-GENERATED by packages/glossary/scripts/generate.ts — DO NOT EDIT.
// Run \`pnpm generate:glossary\` to regenerate. Verified by the \`glossary-roundtrip\` guard.
export const GLOSSARY_IDS = {
${idLines}
} as const;

export type GlossaryId = keyof typeof GLOSSARY_IDS;

export interface GlossaryTerm {
  id: GlossaryId;
  title: string;
  description: string;
  boundedContext: string;
  lang: string;
}

export const GLOSSARY_TERMS: readonly GlossaryTerm[] = [
${termLines}
];
`;
}

async function main(): Promise<void> {
  const terms = await readTerms();

  // 1. ids.ts
  const idsOut = resolve(REPO_ROOT, IDS_OUT);
  await mkdir(dirname(idsOut), { recursive: true });
  await writeFile(idsOut, renderIdsTs(terms), "utf8");

  // 2. i18n label bundles, one per language present. Rewritten from scratch so a
  //    removed/renamed language does not leave a stale bundle behind.
  const messagesRoot = resolve(REPO_ROOT, MESSAGES_DIR);
  await rm(messagesRoot, { recursive: true, force: true });
  const langs = [...new Set(terms.map((t) => t.lang))].sort();
  for (const lang of langs) {
    const bundle: Record<string, { title: string; description: string }> = {};
    for (const t of terms.filter((x) => x.lang === lang)) {
      bundle[t.id] = { title: t.title, description: t.description };
    }
    const outFile = resolve(messagesRoot, lang, "glossary.json");
    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, `${JSON.stringify(bundle, null, 2)}\n`, "utf8");
  }

  process.stdout.write(
    `[generate:glossary] wrote ${IDS_OUT} (${terms.length} ids) + ${langs.length} i18n bundle(s): ${langs.join(", ")}.\n`,
  );
}

main().catch((e) => {
  process.stderr.write(`[generate:glossary] ${(e as Error).stack ?? String(e)}\n`);
  process.exit(1);
});
