// #2213 — the BYTES half of the golden dataset.
//
// The golden rows reference two kinds of object-storage content: an expert's
// portrait (`experts.photo_ref`) and an эфир's programme (`events.program_pdf_ref`).
// A row that names a key no object answers is worse than a null column — the
// doctor page renders a broken portrait and the programme block offers a
// download that 404s — so the seed owns the objects as much as it owns the rows.
//
// Two sources, one shape:
//   * portraits are COMMITTED bytes (`media/portraits/<ordinal>.webp`) — a face
//     cannot be derived from an index, and a seed that reached out to a face
//     generator at run time would not be reproducible;
//   * programmes are GENERATED bytes — a programme is a function of the эфир's
//     own title, instant and speakers, all of which move with the resolved «now»
//     (#2212). Committing 40 PDFs would freeze January into the fixture again.
//
// This module is the ONLY one allowed to import `pdf-lib` and `node:fs`.
// `programme.ts` holds the same programme as pure text lines and is what every
// dataset consumer (and the unit suite) reads; here that text becomes a page.
//
// Resolution note: the portraits are read relative to `import.meta.url`, i.e.
// from `src/`. Every real entry point runs from source (`seed:golden` is
// `tsx src/seed/golden/run.ts`, vitest loads `src` too), and `packages/db`
// ships `src` in its `files`. The compiled `dist` copy carries no media, so a
// consumer that imports this builder from `dist` gets a loud ENOENT naming the
// missing portrait rather than a silently empty plan.

import { readFile } from "node:fs/promises";

import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, rgb, type PDFFont, type PDFPage } from "pdf-lib";

import type { NewExpert } from "../../schema/taxonomy.js";
import type { GoldenDataset } from "./dataset.js";
import {
  eventProgrammeKey,
  formatMskDate,
  formatMskTime,
  ordinalFromExpertPhotoKey,
  programmeLines,
  type ProgrammeSpec,
} from "./programme.js";
import { GOLDEN_VOLUME_ORDINAL_BASE } from "./volume.js";

/**
 * The object store the seed writes its media into.
 *
 * Deliberately three lines wide. The seed needs exactly «is it already there»
 * and «put it there»; anything else (presigning, listing, deletion) belongs to
 * the API's storage port, and a fixture writer that could delete is a fixture
 * writer that can delete the wrong bucket.
 */
export interface GoldenMediaStore {
  exists(key: string): Promise<boolean>;
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
}

/**
 * When an object already present in the store must be written again.
 *
 * `if-absent` belongs to the COMMITTED bytes: a portrait's key and its file
 * both live in git, so an object already in the bucket is the object the plan
 * would upload. `always` belongs to the GENERATED bytes: a programme's key is a
 * function of the ordinal alone (`eventProgrammeKey`) while its content moves
 * with the resolved «now», so the same key legitimately addresses different
 * bytes at every pin and skipping on `exists` would freeze the first pin's
 * dates into a bucket the rows keep moving away from.
 */
export type GoldenMediaRefresh = "always" | "if-absent";

/** One object of the media plan, fully materialised. */
export interface GoldenMediaObject {
  key: string;
  contentType: string;
  bytes: Uint8Array;
  refresh: GoldenMediaRefresh;
}

/** Raised when the dataset names media the seed cannot produce. */
export class GoldenMediaError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GoldenMediaError";
  }
}

export const PORTRAIT_CONTENT_TYPE = "image/webp";
export const PROGRAMME_CONTENT_TYPE = "application/pdf";

/** How many objects are in flight at once — see `writeGoldenMedia`. */
export const GOLDEN_MEDIA_CONCURRENCY = 8;

/**
 * The instant every generated PDF claims it was created at.
 *
 * NOT «now» on purpose. The programme's CONTENT moves with the pin (that is
 * the point of #2212), but two runs at the SAME pin must produce byte-identical
 * objects: the writer re-PUTs every programme on every seed, so without a fixed
 * instant each re-seed would churn the bucket and no `pg_dump`-style diff of it
 * could ever be read. A literal keeps the metadata out of the equation entirely.
 */
const PDF_FIXED_INSTANT = new Date("2026-01-01T00:00:00.000Z");
const PDF_PRODUCER = "Doctor.School golden seed";
const PDF_CREATOR = "packages/db/src/seed/golden/media.ts";

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 56;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

const INK = rgb(0.11, 0.12, 0.14);
const MUTED = rgb(0.42, 0.44, 0.48);

const portraitDir = new URL("./media/portraits/", import.meta.url);
const fontDir = new URL("./media/fonts/", import.meta.url);

let fontBytesCache: Promise<{ regular: Uint8Array; semiBold: Uint8Array }> | null =
  null;

function loadFontBytes(): Promise<{ regular: Uint8Array; semiBold: Uint8Array }> {
  fontBytesCache ??= (async () => ({
    regular: new Uint8Array(await readFile(new URL("Inter-Regular.ttf", fontDir))),
    semiBold: new Uint8Array(
      await readFile(new URL("Inter-SemiBold.ttf", fontDir)),
    ),
  }))();
  return fontBytesCache;
}

/** The volume ordinal a golden uuid addresses. */
function ordinalOf(id: string): number {
  return Number.parseInt(id.slice(-12), 16);
}

/**
 * Derives the programme of every event that publishes one, from the ROWS.
 *
 * Reading the dataset rather than re-deriving from the plan is what makes the
 * PDF and the page agree: the speakers on the page are `event_experts` in
 * `position` order, so the programme cannot drift from the event page even if
 * the slot function changes underneath it.
 */
export function goldenProgrammeSpecs(dataset: GoldenDataset): ProgrammeSpec[] {
  const expertById = new Map(dataset.experts.map((row) => [row.id as string, row]));
  const projectTitleById = new Map(
    dataset.projects.map((row) => [row.id as string, row.title as string]),
  );

  const speakersByEvent = new Map<string, { position: number; name: string; role: string }[]>();
  for (const link of dataset.eventExperts) {
    const expert = expertById.get(link.expertId as string);
    if (!expert) continue;
    const list = speakersByEvent.get(link.eventId as string) ?? [];
    list.push({
      position: link.position as number,
      name: expertFullName(expert),
      role: link.role as string,
    });
    speakersByEvent.set(link.eventId as string, list);
  }

  const projectByEvent = new Map<string, string>();
  for (const link of dataset.eventProjects) {
    const eventId = link.eventId as string;
    if (projectByEvent.has(eventId)) continue;
    const title = projectTitleById.get(link.projectId as string);
    if (title) projectByEvent.set(eventId, title);
  }

  const specs: ProgrammeSpec[] = [];
  for (const event of dataset.events) {
    if (!event.programPdfRef) continue;
    const ordinal = ordinalOf(event.id as string);
    const startsAt = event.startsAt as Date;
    if (!(startsAt instanceof Date)) {
      throw new GoldenMediaError(
        `event ${String(event.slug)} has no startsAt — a programme cannot be dated`,
      );
    }
    const speakers = (speakersByEvent.get(event.id as string) ?? [])
      .sort((a, b) => a.position - b.position)
      .map(({ name, role }) => ({ name, role }));
    specs.push({
      ordinal,
      index: ordinal - GOLDEN_VOLUME_ORDINAL_BASE,
      title: event.title as string,
      startsAt,
      durationMin: event.durationMin as number,
      participationFormat: (event.participationFormat as string) ?? "online",
      school: (event.school as string) ?? "Doctor.School",
      projectTitle: projectByEvent.get(event.id as string) ?? null,
      speakers,
    });
  }
  return specs;
}

function expertFullName(expert: NewExpert): string {
  return [expert.familyName, expert.givenName, expert.patronymic]
    .filter((part): part is string => Boolean(part))
    .join(" ");
}

/**
 * Every object the dataset's rows promise, as bytes.
 *
 * Built in full before a single PUT so that a missing portrait or an
 * unrenderable programme fails the seed BEFORE it has written half a bucket.
 */
export async function buildGoldenMediaPlan(
  dataset: GoldenDataset,
): Promise<GoldenMediaObject[]> {
  const plan: GoldenMediaObject[] = [];

  for (const expert of dataset.experts) {
    const key = expert.photoRef;
    if (!key) continue;
    const ordinal = ordinalFromExpertPhotoKey(key);
    if (ordinal === null) {
      throw new GoldenMediaError(
        `expert ${String(expert.slug)} carries photo_ref "${key}", which is not a golden portrait key`,
      );
    }
    plan.push({
      key,
      contentType: PORTRAIT_CONTENT_TYPE,
      bytes: await readPortrait(ordinal, expert),
      refresh: "if-absent",
    });
  }

  const specs = goldenProgrammeSpecs(dataset);
  for (const spec of specs) {
    plan.push({
      key: eventProgrammeKey(spec.ordinal),
      contentType: PROGRAMME_CONTENT_TYPE,
      bytes: await renderProgrammePdf(spec),
      refresh: "always",
    });
  }

  const seen = new Set<string>();
  for (const object of plan) {
    if (seen.has(object.key)) {
      throw new GoldenMediaError(`media plan repeats key "${object.key}"`);
    }
    seen.add(object.key);
  }
  return plan;
}

async function readPortrait(
  ordinal: number,
  expert: NewExpert,
): Promise<Uint8Array> {
  const file = new URL(`${ordinal}.webp`, portraitDir);
  try {
    return new Uint8Array(await readFile(file));
  } catch (cause) {
    throw new GoldenMediaError(
      `expert ${String(expert.slug)} names portrait ${ordinal}.webp, which is not committed under seed/golden/media/portraits (${
        cause instanceof Error ? cause.message : String(cause)
      })`,
    );
  }
}

/**
 * Renders one programme.
 *
 * The page is laid out from `programmeLines(spec)` — the same strings the unit
 * suite asserts on — so «what the PDF says» has exactly one definition. Only
 * the TYPOGRAPHY is decided here, by the shape of each line.
 */
export async function renderProgrammePdf(
  spec: ProgrammeSpec,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);

  const { regular, semiBold } = await loadFontBytes();
  // `subset: false` embeds the (already Latin+Cyrillic-subset) faces verbatim:
  // the committed TTFs are ~24 KB each, and a verbatim embed is byte-stable by
  // construction, which is the property this whole module is built around.
  const body = await doc.embedFont(regular, { subset: false });
  const strong = await doc.embedFont(semiBold, { subset: false });

  doc.setTitle(`Программа: ${spec.title}`);
  doc.setSubject(`${formatMskDate(spec.startsAt)}, ${formatMskTime(spec.startsAt)} МСК`);
  doc.setAuthor(spec.school);
  doc.setProducer(PDF_PRODUCER);
  doc.setCreator(PDF_CREATOR);
  doc.setCreationDate(PDF_FIXED_INSTANT);
  doc.setModificationDate(PDF_FIXED_INSTANT);

  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  const lines = programmeLines(spec);
  for (const [position, line] of lines.entries()) {
    const style = styleOf(position, line);
    if (line === "") {
      y -= style.size * 0.6;
      continue;
    }
    const font = style.bold ? strong : body;
    for (const piece of wrap(line.trimStart(), font, style.size, style.indent)) {
      if (y - style.size < MARGIN) {
        page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        y = PAGE_HEIGHT - MARGIN;
      }
      y -= style.size * style.leading;
      page.drawText(piece, {
        x: MARGIN + style.indent,
        y,
        size: style.size,
        font,
        color: style.muted ? MUTED : INK,
      });
    }
    y -= style.after;
  }

  drawFooter(page, body, spec);

  return await doc.save({ useObjectStreams: false });
}

interface LineStyle {
  size: number;
  bold: boolean;
  muted: boolean;
  indent: number;
  leading: number;
  after: number;
}

/**
 * Typography by line shape.
 *
 * `programmeLines` emits the school first, the title second and indents a
 * session's speaker by four spaces; the headings are the only all-caps lines.
 * Matching on that keeps the layout rules in one readable place instead of
 * threading a second, parallel «styled lines» structure through `programme.ts`.
 */
function styleOf(position: number, line: string): LineStyle {
  if (position === 0) {
    return { size: 9, bold: false, muted: true, indent: 0, leading: 1.3, after: 4 };
  }
  if (position === 1) {
    return { size: 18, bold: true, muted: false, indent: 0, leading: 1.25, after: 6 };
  }
  if (/^[А-ЯЁ ]+$/u.test(line)) {
    return { size: 11, bold: true, muted: false, indent: 0, leading: 1.6, after: 4 };
  }
  if (line.startsWith("    ")) {
    return { size: 9, bold: false, muted: true, indent: 14, leading: 1.35, after: 1 };
  }
  return { size: 10, bold: false, muted: false, indent: 0, leading: 1.45, after: 2 };
}

/** Greedy word wrap at the content width. */
function wrap(
  line: string,
  font: PDFFont,
  size: number,
  indent: number,
): string[] {
  const width = CONTENT_WIDTH - indent;
  const words = line.split(" ");
  const rows: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current === "" ? word : `${current} ${word}`;
    if (current !== "" && font.widthOfTextAtSize(candidate, size) > width) {
      rows.push(current);
      current = word;
      continue;
    }
    current = candidate;
  }
  rows.push(current);
  return rows;
}

function drawFooter(page: PDFPage, font: PDFFont, spec: ProgrammeSpec): void {
  page.drawText(`${spec.school} · программа эфира`, {
    x: MARGIN,
    y: MARGIN / 2,
    size: 8,
    font,
    color: MUTED,
  });
}

/** What one `writeGoldenMedia` pass did, split by what it did it to. */
export interface GoldenMediaWriteResult {
  /** Objects PUT — every `always` entry plus the absent `if-absent` ones. */
  written: number;
  /** `if-absent` entries the store already had. */
  skipped: number;
}

/**
 * PUTs the generated objects unconditionally and the committed ones once.
 *
 * `exists` is an idempotency test only for bytes that cannot change under a
 * stable key. Portraits qualify: file and key both come from git, so a slot
 * bucket cloned from the template and re-seeded on every `slot up` should not
 * re-upload thirty-four faces. Programmes do not: the key is ordinal-derived
 * and pin-invariant while the page is re-dated at every pin, so skipping them
 * would leave the persistent `main` slot serving a programme that disagrees
 * with its own эфир row for as long as the bucket lives. Bounded concurrency
 * because the target is one MinIO container shared by every live slot.
 */
export async function writeGoldenMedia(
  store: GoldenMediaStore,
  plan: readonly GoldenMediaObject[],
): Promise<GoldenMediaWriteResult> {
  let cursor = 0;
  let written = 0;
  let skipped = 0;
  const worker = async (): Promise<void> => {
    for (;;) {
      const index = cursor;
      cursor += 1;
      if (index >= plan.length) return;
      const object = plan[index] as GoldenMediaObject;
      if (object.refresh === "if-absent" && (await store.exists(object.key))) {
        skipped += 1;
        continue;
      }
      await store.put(object.key, object.bytes, object.contentType);
      written += 1;
    }
  };
  const lanes = Math.min(GOLDEN_MEDIA_CONCURRENCY, plan.length);
  await Promise.all(Array.from({ length: lanes }, () => worker()));
  return { written, skipped };
}

/** One object as the in-memory store holds it — bytes, not a plan entry. */
export type StoredGoldenMediaObject = Omit<GoldenMediaObject, "refresh">;

/** An in-memory store — the unit suite's injection point, never a run-time one. */
export function createInMemoryGoldenMediaStore(): GoldenMediaStore & {
  objects: Map<string, StoredGoldenMediaObject>;
} {
  const objects = new Map<string, StoredGoldenMediaObject>();
  return {
    objects,
    exists: (key) => Promise.resolve(objects.has(key)),
    put: (key, body, contentType) => {
      objects.set(key, { key, contentType, bytes: body });
      return Promise.resolve();
    },
  };
}
