import type { ComboboxOption } from "@ds/design-system/blocks";
import directory from "./settlements.json";

/**
 * 044 EARS-35 — the «Населённый пункт» directory behind the desk entry.
 *
 * SOURCE: `settlements.json` is a byte-for-byte copy of the congress site's
 * bundled ОКТМО directory — repository `doctor-school/orthobio-site`, file
 * `src/data/settlements.json`, generated by `scripts/generate-settlements.mjs`
 * at commit 2151724 (urban settlements only). Regenerate THERE and copy the file
 * again; never edit it here (it is excluded from Prettier to stay identical).
 * The directory now lives in two repositories — tracked in `DEBT.md`; the single
 * future source is an API reference read.
 *
 * The matching rules below mirror that site's `src/lib/settlements.ts` so the
 * registrar's desk resolves a typed place exactly as the participant's own form
 * does: a directory pick carries its region (shown as the hint under the field),
 * anything else — an unlisted or foreign place, a name found in several
 * regions — reveals the «Регион» field the intake requires separately.
 */
interface SettlementDirectory {
  regions: string[];
  places: [string, number][];
}

interface Settlement {
  name: string;
  region: string;
  /** «Химки — Московская область»; a federal city's label is its name alone. */
  label: string;
}

/** How many directory places the open list renders at once. */
export const SETTLEMENT_OPTION_LIMIT = 50;

function settlementLabel(name: string, region: string): string {
  return region === `г. ${name}` ? name : `${name} — ${region}`;
}

const TYPE_PREFIX =
  /^(?:г|гор|город|пгт|рп|кп|дп|гп|п|пос|поселок)(?:\.\s*|\s+)(?=\S)/;
const SEPARATOR = /\s*,\s*|\s+[-–—]\s*|\s*[-–—]\s+/g;

/** Case, «ё», spacing, separators and a leading settlement type folded away. */
function normalisePlace(value: string): string {
  return value
    .toLocaleLowerCase("ru")
    .replace(/ё/g, "е")
    .trim()
    .replace(/\s+/g, " ")
    .replace(SEPARATOR, " - ")
    .replace(TYPE_PREFIX, "");
}

/** The name part of what was typed («Кировск, Мурманская» → «кировск»). */
function nameQuery(typed: string): string {
  return normalisePlace(typed).split(" - ")[0] ?? "";
}

interface Keyed {
  entry: Settlement;
  name: string;
  label: string;
}

let keyedCache: Keyed[] | null = null;

/** Expanded on first use: the module import stays cheap until the field opens. */
function keyed(): Keyed[] {
  if (keyedCache) return keyedCache;
  const { regions, places } = directory as SettlementDirectory;
  keyedCache = places.map(([name, i]) => {
    const region = regions[i];
    if (region === undefined) {
      throw new Error(`settlements: no region #${i} for «${name}»`);
    }
    const label = settlementLabel(name, region);
    return {
      entry: { name, region, label },
      name: normalisePlace(name),
      label: normalisePlace(label),
    };
  });
  return keyedCache;
}

const DIRECTORY_PREFIX = "dir:";
const FREE_PREFIX = "free:";

/** The option value of a typed place taken as written. */
export function freeSettlementValue(typed: string): string {
  return `${FREE_PREFIX}${typed}`;
}

/** The typed text a free option value carries, or `null` for a directory one. */
export function freeSettlementText(value: string): string | null {
  return value.startsWith(FREE_PREFIX) ? value.slice(FREE_PREFIX.length) : null;
}

function toOption(item: Keyed, index: number): ComboboxOption {
  const { name, region, label } = item.entry;
  return {
    value: `${DIRECTORY_PREFIX}${index}`,
    label: name,
    ...(label !== name ? { description: region } : {}),
  };
}

/**
 * The directory places whose name BEGINS with what was typed, capped: the
 * directory has thousands of places and the list narrows as the registrar types.
 */
export function settlementOptions(
  typed: string,
  limit: number = SETTLEMENT_OPTION_LIMIT,
): ComboboxOption[] {
  const needle = nameQuery(typed);
  const options: ComboboxOption[] = [];
  const all = keyed();
  for (let i = 0; i < all.length && options.length < limit; i += 1) {
    const item = all[i]!;
    if (item.name.startsWith(needle)) options.push(toOption(item, i));
  }
  return options;
}

/** The directory option a stored value points at (to keep its label shown). */
export function settlementOption(value: string): ComboboxOption | null {
  if (!value.startsWith(DIRECTORY_PREFIX)) return null;
  const index = Number(value.slice(DIRECTORY_PREFIX.length));
  const item = Number.isInteger(index) ? keyed()[index] : undefined;
  return item ? toOption(item, index) : null;
}

/** What the form holds once a settlement option is committed. */
export interface SettlementResolution {
  city: string;
  /** Filled for a directory place; empty when the «Регион» field must ask. */
  region: string;
  /** The region line under the field; empty for a federal city or a free place. */
  hint: string;
  /** Why the «Регион» field is revealed, or `null` when the region is known. */
  regionField: null | "unknown" | "ambiguous";
}

function resolved({ name, region, label }: Settlement): SettlementResolution {
  return {
    city: name,
    region,
    hint: label !== name ? region : "",
    regionField: null,
  };
}

export function resolveSettlement(value: string): SettlementResolution | null {
  const free = freeSettlementText(value);
  if (free === null) {
    const index = Number(value.slice(DIRECTORY_PREFIX.length));
    const item = Number.isInteger(index) ? keyed()[index] : undefined;
    return item ? resolved(item.entry) : null;
  }
  const typed = free.trim().replace(/\s+/g, " ");
  const needle = normalisePlace(typed);
  if (needle === "") return null;
  const byLabel = keyed().find((k) => k.label === needle);
  if (byLabel) return resolved(byLabel.entry);
  const byName = keyed().filter((k) => k.name === needle);
  if (byName.length === 1) return resolved(byName[0]!.entry);
  // Several regions hold this name: the typed name stands in its directory
  // spelling, and the region is asked for.
  const city = byName[0]?.entry.name ?? typed;
  const regionField = byName.length > 1 ? "ambiguous" : "unknown";
  return { city, region: "", hint: "", regionField };
}
