import "reflect-metadata";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";
import { format } from "prettier";
import { cleanupOpenApiDoc } from "nestjs-zod";
// Import the production compiler output, not tsx-transpiled controller source:
// decorator type metadata is what Swagger uses for createZodDto request bodies.
import { createApiApplication } from "../dist/api-application.js";
import {
  reconcileGeneratedFiles,
  stableJson,
} from "../../../tools/scripts/generate-api-client-lib.mjs";

const repositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../..",
);
const snapshotPath = resolve(
  repositoryRoot,
  "packages/api-client/openapi.snapshot.json",
);
const sdkPath = resolve(
  repositoryRoot,
  "packages/api-client/src/types.generated.ts",
);
const check = process.argv.includes("--check");

async function generate(): Promise<void> {
  // AppModule's real DatabaseModule constructs a lazy pg Pool during DI. A
  // syntactically valid non-routable URL keeps generation hermetic: without
  // app.init()/listen() no connection or lifecycle hook is attempted.
  process.env.DATABASE_URL ??=
    "postgresql://openapi:openapi@127.0.0.1:1/openapi";
  process.env.AUDIT_IDENTIFIER_PEPPER ??= "openapi-generation-only";
  process.env.LIFECYCLE_IMPACT_TOKEN_SECRET ??= "openapi-generation-only";
  // Creating the full HTTP application (without init/listen) lets Swagger scan
  // every real controller while avoiding DB connections and lifecycle hooks.
  const app = await createApiApplication({
    logger: false,
    abortOnError: false,
  });
  console.log("API container created; generating OpenAPI document");
  try {
    const config = new DocumentBuilder()
      .setTitle("DS Platform API")
      .setVersion("1.0.0")
      .addBearerAuth()
      .build();
    const document = cleanupOpenApiDoc(
      SwaggerModule.createDocument(app, config, {
        operationIdFactory: (controller, method) => `${controller}_${method}`,
      }),
      { version: "3.1" },
    ) as OpenAPI3;
    document.openapi = "3.1.0";
    Object.assign(document, {
      "x-generated-by":
        "pnpm generate:api-client (check: pnpm generate:api-client --check)",
    });

    // JSON output also passes the repository's staged Prettier hook, so emit
    // that canonical form directly rather than letting a commit rewrite it.
    const snapshot = await format(stableJson(document), { parser: "json" });
    const ast = await openapiTS(document, { alphabetize: true, silent: true });
    console.log("OpenAPI document converted to TypeScript");
    const sdk = [
      "/**",
      " * AUTO-GENERATED by `pnpm generate:api-client`.",
      " * Check freshness with `pnpm generate:api-client --check`.",
      " * Do not edit this file manually; edit the Zod/Nest contract instead.",
      " */",
      astToString(ast).replace(/^\/\*\*[\s\S]*?\*\/\s*/, ""),
    ].join("\n");

    await reconcileGeneratedFiles(
      new Map([
        [snapshotPath, snapshot],
        [sdkPath, sdk.endsWith("\n") ? sdk : `${sdk}\n`],
      ]),
      { check },
    );
    console.log(
      check
        ? "Generated API artifacts are current"
        : "Generated API artifacts updated",
    );
  } finally {
    console.log("Closing API container");
    await app.close();
  }
}

generate().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
