/**
 * Pure matrix logic — validation (§3.1 / §6.2) and Markdown projection (§5).
 *
 * Framework-free on purpose: route discovery (which needs @nestjs/core) lives in
 * authz.discovery.ts, so this module — the security-critical "is this row valid"
 * judgement — is trivially unit-testable without booting Nest or a database.
 */
import { ROLES, type AuthzMeta } from "./authz.types.js";

const ACCESS = new Set(["public", "authenticated"]);
const CHECK = new Set(["none", "fast-path", "policy"]);
const AUDIT = new Set(["none", "low-stakes", "high-stakes"]);
const ROLE_SET = new Set<string>(ROLES);

const EM_DASH = "—";

/** One projected row: the derived endpoint plus its authored classification. */
export interface MatrixRow {
  endpoint: string;
  meta: AuthzMeta;
}

/**
 * Validate one row's metadata against the §6.2 completeness/validity rules and
 * the §3.1 field interdependencies. Returns a list of human-readable violation
 * messages — empty means the row is a valid, complete classification.
 *
 * `meta` is intentionally typed loosely: the gate reads raw Nest metadata, which
 * may be entirely absent (a handler with no `@Authz`) or partially authored.
 */
export function validateRow(
  endpoint: string,
  meta: Partial<AuthzMeta> | undefined,
): string[] {
  if (meta == null) {
    return [`${endpoint}: missing @Authz metadata (handler is unclassified)`];
  }
  const v: string[] = [];
  const at = (m: string): void => void v.push(`${endpoint}: ${m}`);

  const { access, check, audit, roles, objectAttrs, tests } = meta;

  // ── Required fields + enum validity (§6.2) ──────────────────────────────
  if (access === undefined) at("`access` is required");
  else if (!ACCESS.has(access)) at(`\`access\` has invalid value "${access}"`);

  if (check === undefined) at("`auth_check` is required");
  else if (!CHECK.has(check)) at(`\`auth_check\` has invalid value "${check}"`);

  if (audit === undefined) at("`audit` is required");
  else if (!AUDIT.has(audit)) at(`\`audit\` has invalid value "${audit}"`);

  if (!Array.isArray(tests) || tests.length === 0)
    at("`tests` must list at least one EARS id (every row is test-covered)");

  if (Array.isArray(roles)) {
    for (const r of roles)
      if (!ROLE_SET.has(r)) at(`\`required_roles\` has unknown role "${r}"`);
  }

  // ── Interdependencies (§3.1) ────────────────────────────────────────────
  const hasRoles = Array.isArray(roles) && roles.length > 0;
  const hasAttrs = Array.isArray(objectAttrs) && objectAttrs.length > 0;

  if (access === "public") {
    if (check !== undefined && check !== "none")
      at("`access: public` requires `auth_check: none`");
    if (hasRoles) at("`access: public` must not carry `required_roles`");
    if (hasAttrs) at("`access: public` must not carry `object_attrs`");
  }

  if (access === "authenticated") {
    if (!hasRoles)
      at("`access: authenticated` requires a non-empty `required_roles`");
    if (check === "none")
      at("`access: authenticated` requires `auth_check` in {fast-path, policy}");
  }

  if (hasAttrs && check !== "policy")
    at("`object_attrs` is only valid with `auth_check: policy`");

  return v;
}

/**
 * Build the derived `METHOD /vN/path` endpoint identifier (§3 `endpoint` column)
 * from the route's method, version, controller path, and handler path.
 */
export function assembleEndpoint(
  method: string,
  version: string | undefined,
  controllerPath: string,
  handlerPath: string,
): string {
  const segments = [`v${version ?? "1"}`, controllerPath, handlerPath]
    .join("/")
    .split("/")
    .filter((s) => s.length > 0);
  return `${method.toUpperCase()} /${segments.join("/")}`;
}

const BANNER =
  "<!-- GENERATED by tools/lint/endpoint-authz-lint.ts --generate — do not edit by hand -->";

const HEADERS = [
  "endpoint",
  "access",
  "required_roles",
  "auth_check",
  "object_attrs",
  "step_up",
  "audit",
  "test_coverage",
] as const;

function cells(row: MatrixRow): string[] {
  const m = row.meta;
  return [
    row.endpoint,
    m.access,
    m.roles && m.roles.length > 0 ? m.roles.join(", ") : EM_DASH,
    m.check,
    m.objectAttrs && m.objectAttrs.length > 0
      ? m.objectAttrs.join("; ")
      : EM_DASH,
    m.stepUp ? "true" : "false",
    m.audit,
    m.tests.join(", "),
  ];
}

/**
 * Render the aggregated matrix as Markdown (§5). Deterministic: rows are sorted
 * by `endpoint` and every value is fixed by the input, so identical input yields
 * byte-identical output (the property the drift gate depends on). The result is
 * a raw table; the CLI runs it through Prettier at the I/O boundary so the
 * committed file matches lint-staged formatting.
 */
export function renderMatrix(rows: MatrixRow[]): string {
  // Code-point sort (not localeCompare): the result feeds a byte-exact drift
  // gate, so ordering must not depend on the runner's locale/ICU.
  const sorted = [...rows].sort((a, b) =>
    a.endpoint < b.endpoint ? -1 : a.endpoint > b.endpoint ? 1 : 0,
  );
  const lines = [
    BANNER,
    "",
    `| ${HEADERS.join(" | ")} |`,
    `| ${HEADERS.map(() => "---").join(" | ")} |`,
    ...sorted.map((r) => `| ${cells(r).join(" | ")} |`),
    "",
  ];
  return lines.join("\n");
}
