import { describe, expect, it } from "vitest";
import {
  assembleEndpoint,
  renderMatrix,
  validateRow,
  type MatrixRow,
} from "./authz.matrix.js";
import type { AuthzMeta } from "./authz.types.js";

const publicMeta: AuthzMeta = {
  access: "public",
  check: "none",
  audit: "high-stakes",
  tests: ["EARS-5"],
};

const authedMeta: AuthzMeta = {
  access: "authenticated",
  roles: ["doctor_guest"],
  check: "fast-path",
  audit: "low-stakes",
  tests: ["EARS-10"],
};

describe("validateRow", () => {
  it("accepts a well-formed public row", () => {
    expect(validateRow("POST /v1/auth/login", publicMeta)).toEqual([]);
  });

  it("accepts a well-formed authenticated fast-path row", () => {
    expect(validateRow("DELETE /v1/auth/session", authedMeta)).toEqual([]);
  });

  it("accepts a policy row carrying object_attrs", () => {
    const meta: AuthzMeta = {
      access: "authenticated",
      roles: ["doctor_guest"],
      check: "policy",
      objectAttrs: ["course.author_id == actor.id"],
      audit: "high-stakes",
      tests: ["EARS-99"],
    };
    expect(validateRow("PATCH /v1/courses/:id", meta)).toEqual([]);
  });

  // §6.2 Incomplete — required fields absent on every row.
  it("§6.2: flags absent metadata as a violation", () => {
    expect(validateRow("GET /v1/x", undefined).length).toBeGreaterThan(0);
  });

  it("§6.2: flags an empty tests array on every row regardless of access", () => {
    const v = validateRow("POST /v1/auth/login", { ...publicMeta, tests: [] });
    expect(v.some((m) => /tests/i.test(m))).toBe(true);
  });

  it("§6.2: flags a missing audit field", () => {
    const { audit: _omit, ...rest } = publicMeta;
    const v = validateRow("POST /v1/auth/login", rest as AuthzMeta);
    expect(v.some((m) => /audit/i.test(m))).toBe(true);
  });

  // §3.1 interdependencies.
  it("§3.1: rejects access:public with a non-none auth_check", () => {
    const v = validateRow("POST /v1/auth/login", {
      ...publicMeta,
      check: "fast-path",
    });
    expect(v.length).toBeGreaterThan(0);
  });

  it("§3.1: rejects access:public carrying required_roles", () => {
    const v = validateRow("POST /v1/auth/login", {
      ...publicMeta,
      roles: ["doctor_guest"],
    });
    expect(v.length).toBeGreaterThan(0);
  });

  it("§3.1: rejects access:authenticated with empty required_roles", () => {
    const v = validateRow("DELETE /v1/auth/session", {
      ...authedMeta,
      roles: [],
    });
    expect(v.some((m) => /role/i.test(m))).toBe(true);
  });

  it("§3.1: rejects access:authenticated with auth_check:none", () => {
    const v = validateRow("DELETE /v1/auth/session", {
      ...authedMeta,
      check: "none",
    });
    expect(v.length).toBeGreaterThan(0);
  });

  it("§3.1: rejects object_attrs present with auth_check:fast-path", () => {
    const v = validateRow("DELETE /v1/auth/session", {
      ...authedMeta,
      objectAttrs: ["x == y"],
    });
    expect(v.length).toBeGreaterThan(0);
  });

  it("§6.2: rejects an out-of-enum role", () => {
    const v = validateRow("DELETE /v1/auth/session", {
      ...authedMeta,
      roles: ["wizard" as never],
    });
    expect(v.some((m) => /role/i.test(m))).toBe(true);
  });

  it("§6.2: rejects an out-of-enum auth_check", () => {
    const v = validateRow("GET /v1/x", {
      ...publicMeta,
      check: "magic" as never,
    });
    expect(v.length).toBeGreaterThan(0);
  });
});

describe("assembleEndpoint", () => {
  it("builds METHOD /vN/path from controller + handler segments", () => {
    expect(assembleEndpoint("GET", "1", "health", "")).toBe("GET /v1/health");
    expect(assembleEndpoint("DELETE", "1", "auth", "session")).toBe(
      "DELETE /v1/auth/session",
    );
  });

  it("defaults to v1 and normalizes stray slashes", () => {
    expect(assembleEndpoint("POST", undefined, "/auth/", "/login/")).toBe(
      "POST /v1/auth/login",
    );
  });
});

describe("renderMatrix", () => {
  const rows: MatrixRow[] = [
    { endpoint: "DELETE /v1/auth/session", meta: authedMeta },
    { endpoint: "POST /v1/auth/login", meta: publicMeta },
  ];

  it("emits the do-not-edit banner", () => {
    expect(renderMatrix(rows)).toContain(
      "GENERATED by tools/lint/endpoint-authz-lint.ts",
    );
  });

  it("sorts rows by endpoint", () => {
    const out = renderMatrix(rows);
    expect(out.indexOf("DELETE /v1/auth/session")).toBeLessThan(
      out.indexOf("POST /v1/auth/login"),
    );
  });

  it("renders — for empty required_roles/object_attrs and joins multi-values", () => {
    const out = renderMatrix([
      {
        endpoint: "POST /v1/auth/register",
        meta: {
          access: "public",
          check: "none",
          audit: "high-stakes",
          tests: ["EARS-1", "EARS-2"],
        },
      },
    ]);
    // public row: required_roles and object_attrs both render as the em dash.
    expect(out).toMatch(/POST \/v1\/auth\/register\s*\|\s*public\s*\|\s*—/);
    // multi-value tests joined.
    expect(out).toContain("EARS-1, EARS-2");
  });

  it("is deterministic — identical input yields byte-identical output", () => {
    expect(renderMatrix(rows)).toBe(renderMatrix(rows));
  });
});
